name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker to use Minikube's environment
    - name: Set up Docker to use Minikube's environment
      run: |
        # Start Minikube if it's not already running
        minikube start --driver=docker
        
        # Export Docker environment variables for Minikube to use
        echo "export DOCKER_TLS_VERIFY='1'" >> $GITHUB_ENV
        echo "export DOCKER_HOST='tcp://$(minikube ip):2376'" >> $GITHUB_ENV
        echo "export DOCKER_CERT_PATH=$(minikube docker-env | grep DOCKER_CERT_PATH | sed 's/^.*=//')" >> $GITHUB_ENV
        echo "export DOCKER_MACHINE_NAME=minikube" >> $GITHUB_ENV

    # Build frontend image
    - name: Build Frontend Docker Image
      run: docker build -t unzila/frontend-app:latest -f frontend/Dockerfile .

    # Build backend image
    - name: Build Backend Docker Image
      run: docker build -t unzila/backend-app:latest -f backend/Dockerfile .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Push frontend image
    - name: Push Frontend Docker Image
      run: docker push unzila/frontend-app:latest

    # Push backend image
    - name: Push Backend Docker Image
      run: docker push unzila/backend-app:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8/backend-deployment.yaml
        kubectl apply -f k8/backend-service.yaml
        kubectl apply -f k8/frontend-deployment.yaml
        kubectl apply -f k8/frontend-service.yaml
